name: searcheable_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter



  intl: ^0.18.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6

  loadmore_listview: ^1.0.7
  time_scheduler_table: ^1.0.1
  calendar_view: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
