# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Fluter Furshed

on:
 push:
    branches: [ "main" ]
 pull_request:
   branches:
     - "build-**"
   paths-ignore:
     - "docs/**"
     - "drz-swagger/**"
     - ".vscode/**"
     - ".idea/"
     - "**/README.md"
     - "README.md"
     - ".github/**"


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:     
      - uses: actions/checkout@v3
      - name: Create key.properties
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > /home/runner/keystore.jks
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
          # cache: 'gradle'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          # cache: true

      - name: Get dependencies
        working-directory: ./2.flutter/furshed
        run: flutter pub get

      # - name: Analyze project source
      #   run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Run build apk
        working-directory: ./2.flutter/furshed
        run: flutter build apk --release
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_FILE: "/home/runner/keystore.jks"
      - name: Upload Android Release
        # working-directory: ./2.flutter/furshed
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: build/app/outputs/apk/dev/debug/apk_name.apk
