# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Fluter Furshed

on:
 push:
    branches: [ "main" ]
 pull_request:
   branches:
     - "build-**"
   paths-ignore:
     - "docs/**"
     - "drz-swagger/**"
     - ".vscode/**"
     - ".idea/"
     - "**/README.md"
     - "README.md"
     - ".github/**"


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:     
      - uses: actions/checkout@v3
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          secrets: inherit
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
          # cache: 'gradle'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          # cache: true

      - name: Get dependencies
        working-directory: ./2.flutter/furshed
        run: flutter pub get

      # - name: Analyze project source
      #   run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Run build apk
        working-directory: ./2.flutter/furshed
        run: flutter build apk --release
      - name: Upload Android Release
        # working-directory: ./2.flutter/furshed
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: build/app/outputs/apk/dev/debug/apk_name.apk
