# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Fluter Furshed

on:
 push:
    branches: [ "main" ]
 pull_request:
   branches:
     - "build-**"
   paths-ignore:
     - "docs/**"
     - "drz-swagger/**"
     - ".vscode/**"
     - ".idea/"
     - "**/README.md"


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:     
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v1
        with:
          java-version: "21.x"
          # cache: 'gradle'

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.24.5"
          channel: "stable"
          # cache: true

      - name: Get dependencies
        working-directory: ./2.flutter/furshed
        run: flutter pub get

      # - name: Analyze project source
      #   run: flutter analyze

      # - name: Run tests
      #   run: flutter test

      - name: Run build apk
        working-directory: ./2.flutter/furshed
        run: flutter build apk --release
